# Keybinds

[keybinds]
"Mod+T" = "spawn:kitty"
"Ctrl+Alt+W" = "spawn:noctalia msg wallpaper-random"
"Ctrl+Alt+Delete" = "spawn:noctalia msg panel-toggle session"
"Mod+W" = "spawn:noctalia msg panel-toggle wallpaper"
"Mod+A" = "spawn:noctalia msg panel-toggle launcher"
"Mod+Z" = "spawn:noctalia msg panel-toggle launcher /emo"
"Mod+V" = "spawn:noctalia msg panel-toggle clipboard"
"Mod+X" = "spawn:noctalia msg bar-toggle"
"Mod+P" = "spawn:noctalia msg panel-toggle control-center"
"Mod+Shift+T" = "spawn:noctalia msg panel-toggle test"
"Mod+Comma" = "spawn:noctalia msg settings-toggle"
"F5" = "spawn:noctalia msg volume-down"
"F6" = "spawn:noctalia msg volume-up"
"Mod+Q" = "window-close"
"Mod+Left" = "window-focus-left"
"Mod+Down" = "window-focus-down"
"Mod+Up" = "window-focus-up"
"Mod+Right" = "window-focus-right"
"Mod+Ctrl+Left" = "column-move-left"
"Mod+Ctrl+Down" = "window-move-down"
"Mod+Ctrl+Up" = "window-move-up"
"Mod+Ctrl+Right" = "column-move-right"
"Mod+Home" = "workspace-switch:1"
"Mod+End" = "workspace-switch:9"
"Mod+Shift+Left" = "output-focus-left"
"Mod+Shift+Down" = "output-focus-down"
"Mod+Shift+Up" = "output-focus-up"
"Mod+Shift+Right" = "output-focus-right"
"Mod+Shift+Ctrl+Left" = "column-move-to-output-left"
"Mod+Shift+Ctrl+Down" = "column-move-to-output-down"
"Mod+Shift+Ctrl+Up" = "column-move-to-output-up"
"Mod+Shift+Ctrl+Right" = "column-move-to-output-right"
"Mod+WheelUp" = { action = "workspace-previous", cooldown_ms = 150 }
"Mod+WheelDown" = { action = "workspace-next", cooldown_ms = 150 }
"Mod+Ctrl+WheelUp" = { action = "window-move-to-workspace-previous", cooldown_ms = 150 }
"Mod+Ctrl+WheelDown" = { action = "window-move-to-workspace-next", cooldown_ms = 150 }
"Mod+Shift+WheelUp" = { action = "column-move-left", cooldown_ms = 150 }
"Mod+Shift+WheelDown" = { action = "column-move-right", cooldown_ms = 150 }
"Mod+Page_Down" = "workspace-next"
"Mod+Page_Up" = "workspace-previous"
"Mod+Ctrl+Page_Down" = "window-move-to-workspace-next"
"Mod+Ctrl+Page_Up" = "window-move-to-workspace-previous"
"Mod+1" = "workspace-switch:1"
"Mod+2" = "workspace-switch:2"
"Mod+3" = "workspace-switch:3"
"Mod+4" = "workspace-switch:4"
"Mod+5" = "workspace-switch:5"
"Mod+6" = "workspace-switch:6"
"Mod+7" = "workspace-switch:7"
"Mod+8" = "workspace-switch:8"
"Mod+9" = "workspace-switch:9"
"Mod+Shift+1" = "window-move-to-workspace:1"
"Mod+Shift+2" = "window-move-to-workspace:2"
"Mod+Shift+3" = "window-move-to-workspace:3"
"Mod+Shift+4" = "window-move-to-workspace:4"
"Mod+Shift+5" = "window-move-to-workspace:5"
"Mod+Shift+6" = "window-move-to-workspace:6"
"Mod+Shift+7" = "window-move-to-workspace:7"
"Mod+Shift+8" = "window-move-to-workspace:8"
"Mod+Shift+9" = "window-move-to-workspace:9"
"Mod+BracketLeft" = "window-consume-left"
"Mod+BracketRight" = "window-consume-right"
"Mod+R" = "window-cycle-width"
"Mod+Ctrl+R" = "window-toggle-maximize-to-edges"
"Mod+F" = "window-toggle-maximize"
"Mod+E" = "spawn:nautilus"
"Mod+N" = "workspace-set-layout:toggle"
"Mod+O" = "overview-toggle"
"Mod+Minus" = "window-modify-width:-0.1"
"Mod+Equal" = "window-modify-width:0.1"
"Mod+C" = "window-toggle-floating"
"Mod+Shift+S" = "spawn:noctalia msg screenshot-region"
"Print" = "spawn:noctalia msg screenshot-fullscreen"
"Alt+F" = "window-toggle-fullscreen"
"Alt+Tab" = "spawn:noctalia msg window-switcher"
"Mod+MouseMiddle" = "layout-scroll-drag"
