# Rules

# Gaming
# [[window_rule]]
# match.content_type = "game"
# vrr = "disabled"
# tearing = true
# hdr = "off"
# For Proton/Wine fullscreen: match.xdg_tag = "^proton-game$" + default_fullscreen = true

# Global blur
[[window_rule]]
blur = true
blur_optimized = false
blur_popups = true
blur_ignore_alpha = 0.05

[[window_rule]]
opacity = 0.94

# Opaque media
[[window_rule]]
match.content_type = "game"
blur = false
opacity = 1.0

[[window_rule]]
match.content_type = "video"
blur = false
opacity = 1.0

[[window_rule]]
match.content_type = "photo"
blur = false
opacity = 1.0

# App opacity
[[window_rule]]
match.app_id = "^(Alacritty|kitty|ghostty|foot)$"
opacity = 0.9

[[window_rule]]
match.app_id = "[Vv]esktop|[Dd]iscord|brave-browser|firefox|chromium|helium"
opacity = 0.93

# Nautilus stable
[[window_rule]]
match.app_id = "org.gnome.Nautilus|org.gnome.Settings|org.gnome.Loupe"
blur = true
blur_optimized = false
blur_popups = false
blur_ignore_alpha = 0.2
opacity = 1.0

[[window_rule]]
match.app_id = "blender"
default_floating = false

[[window_rule]]
match.app_id = "brave-browser"
default_floating = false

[[window_rule]]
match.app_id = "org.gnome.Loupe"
default_floating = true

[[window_rule]]
match.app_id = "kvantummanager|qt5ct|qt6ct|nwg-look|org.kde.ark|org.pulseaudio.pavucontrol|blueman-manager"
default_floating = true

[[window_rule]]
match.title = "^Open$|^Save As$|^Choose Files$|^File Operation Progress$"
default_floating = true

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = false
default_size = [800, 600]

# Layer rules
[[layer_rule]]
match.namespace = "^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd|desktop-widget-[^\"]*)$"
blur = true
blur_ignore_alpha = 0.5
blur_optimized = false
blur_popups = true

# Security
# [[security_context_rule]]
# match.sandbox_engine = 'org\.flatpak'
# match.app_id = 'org\.example\.ClipboardManager'
# allow_globals = ["ext_data_control_manager_v1", "zwlr_data_control_manager_v1"]
